const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const appRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(appRoot, "..", "..");

const IOS_ZIP_NAME = "ffmpeg-kit-ios-full-gpl-latest.zip";
const ANDROID_AAR_NAME = "ffmpeg-kit-full-gpl.aar";

const ensureBinariesRelocated = () => {
  console.log("📦 Setting up FFmpeg binaries...");

  const iosZipSourceRoot = path.join(repoRoot, IOS_ZIP_NAME);
  const androidAarSourceRoot = path.join(repoRoot, ANDROID_AAR_NAME);
  const iosZipSourceApp = path.join(appRoot, IOS_ZIP_NAME);
  const androidAarSourceApp = path.join(appRoot, ANDROID_AAR_NAME);

  const iosZipSource = fs.existsSync(iosZipSourceRoot)
    ? iosZipSourceRoot
    : iosZipSourceApp;
  const androidAarSource = fs.existsSync(androidAarSourceRoot)
    ? androidAarSourceRoot
    : androidAarSourceApp;

  const missing = [];
  if (!fs.existsSync(iosZipSource)) {
    missing.push(IOS_ZIP_NAME);
  }
  if (!fs.existsSync(androidAarSource)) {
    missing.push(ANDROID_AAR_NAME);
  }

  if (missing.length > 0) {
    console.error("❌ Missing required FFmpeg binaries at project root:");
    missing.forEach((name) => console.error(`   - ${name}`));
    console.error(
      "Place these files in the repository root and re-run yarn install.",
    );
    process.exit(1);
  }

  const iosTargetDir = path.join(appRoot, "ios", "libs");
  const iosTargetFile = path.join(iosTargetDir, IOS_ZIP_NAME);
  const iosExtractDir = path.join(
    iosTargetDir,
    "ffmpeg-kit-ios-full-gpl-latest",
  );

  const androidTargetDir = path.join(appRoot, "android", "libs");
  const androidTargetFile = path.join(androidTargetDir, ANDROID_AAR_NAME);

  if (!fs.existsSync(iosTargetDir)) {
    console.log(`📁 Creating directory: ${iosTargetDir}`);
    fs.mkdirSync(iosTargetDir, { recursive: true });
  }
  if (!fs.existsSync(androidTargetDir)) {
    console.log(`📁 Creating directory: ${androidTargetDir}`);
    fs.mkdirSync(androidTargetDir, { recursive: true });
  }

  if (!fs.existsSync(iosTargetFile)) {
    fs.copyFileSync(iosZipSource, iosTargetFile);
    console.log(`✅ iOS FFmpeg zip copied to: ${iosTargetFile}`);
  } else {
    console.log("ℹ️ iOS FFmpeg zip already present. Skipping copy.");
  }

  if (!fs.existsSync(iosExtractDir)) {
    console.log(
      `📂 Extracting iOS FFmpeg zip into: ${iosExtractDir} (using system unzip)`,
    );
    try {
      fs.mkdirSync(iosExtractDir, { recursive: true });
      execSync(`unzip -oq "${iosTargetFile}" -d "${iosExtractDir}"`, {
        stdio: "inherit",
      });
      console.log("✅ iOS FFmpeg zip extracted.");
    } catch (err) {
      console.error(
        `❌ Failed to extract iOS FFmpeg zip: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
      process.exit(1);
    }
  } else {
    console.log("ℹ️ iOS FFmpeg frameworks already extracted. Skipping unzip.");
  }

  if (!fs.existsSync(androidTargetFile)) {
    fs.copyFileSync(androidAarSource, androidTargetFile);
    console.log(`✅ Android FFmpeg AAR copied to: ${androidTargetFile}`);
  } else {
    console.log("ℹ️ Android FFmpeg AAR already present. Skipping copy.");
  }
};

const ensureIosPodspec = () => {
  const iosDir = path.join(appRoot, "ios");
  const podspecPath = path.join(iosDir, "ffmpeg-kit-ios-full-gpl.podspec");

  if (!fs.existsSync(iosDir)) {
    return;
  }

  const podspecContent = `# Auto-generated by scripts/manage-ffmpeg.js
Pod::Spec.new do |s|
  s.name             = 'ffmpeg-kit-ios-full-gpl'
  s.version          = '6.0'
  s.summary          = 'Custom full-gpl FFmpegKit iOS frameworks from NooruddinLakhani.'
  s.homepage         = 'https://github.com/NooruddinLakhani/ffmpeg-kit-ios-full-gpl'
  s.license          = { :type => 'LGPL' }
  s.author           = { 'NooruddinLakhani' => 'https://github.com/NooruddinLakhani' }
  s.platform         = :ios, '12.1'
  s.static_framework = true

  # Use local zip file via file:// URL.
  s.source = { :http => "file://#{__dir__}/libs/#{IOS_ZIP_NAME}" }

  s.vendored_frameworks = [
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libswscale.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libswresample.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libavutil.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libavformat.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libavfilter.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libavdevice.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/libavcodec.xcframework',
    'ffmpeg-kit-ios-full-gpl/6.0-80adc/ffmpegkit.xcframework'
  ]
end
`;

  let shouldWrite = true;
  if (fs.existsSync(podspecPath)) {
    const existing = fs.readFileSync(podspecPath, "utf8");
    if (
      existing.includes(
        "ffmpeg-kit-ios-full-gpl-latest/ffmpeg-kit-ios-full-gpl",
      )
    ) {
      shouldWrite = false;
    }
  }

  if (shouldWrite) {
    fs.writeFileSync(podspecPath, podspecContent);
    console.log(`✅ Wrote iOS podspec: ${podspecPath}`);
  } else {
    console.log("ℹ️ iOS podspec already configured. Skipping.");
  }
};

const ensureIosPodfile = () => {
  const podfilePath = path.join(appRoot, "ios", "Podfile");
  if (!fs.existsSync(podfilePath)) {
    return;
  }

  let content = fs.readFileSync(podfilePath, "utf8");

  if (content.includes("ffmpeg-kit-ios-full-gpl.podspec")) {
    console.log("ℹ️ Podfile already patched for FFmpegKit (iOS).");
    return;
  }

  content = content.replace(/^\s*pod\s+'ffmpeg-kit-ios-https'.*$/m, "");

  const insertLine =
    "  pod 'ffmpeg-kit-ios-full-gpl', :podspec => './ffmpeg-kit-ios-full-gpl.podspec'\n" +
    "  pod 'ffmpeg-kit-react-native', :subspecs => ['full-gpl'], :podspec => '../../../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'\n";

  const targetMatch = content.match(/target 'CaseScriptAI' do\n/);
  if (targetMatch) {
    const index = content.indexOf(targetMatch[0]) + targetMatch[0].length;
    content = content.slice(0, index) + insertLine + content.slice(index);
  } else {
    content += `\n${insertLine}`;
  }

  fs.writeFileSync(podfilePath, content);
  console.log("✅ Patched Podfile for FFmpegKit (iOS).");
};

const ensureAndroidAppGradle = () => {
  const appGradlePath = path.join(appRoot, "android", "app", "build.gradle");
  if (!fs.existsSync(appGradlePath)) {
    return;
  }

  let content = fs.readFileSync(appGradlePath, "utf8");

  if (!content.includes('dirs "$rootDir/libs"')) {
    const androidBlockMatch = content.match(/android\s*{[^}]*}/m);
    if (androidBlockMatch) {
      const insert = `\n    repositories {\n        flatDir {\n            dirs "$rootDir/libs"\n        }\n    }\n`;
      const idx =
        content.indexOf(androidBlockMatch[0]) +
        androidBlockMatch[0].lastIndexOf("}");
      content = content.slice(0, idx) + insert + content.slice(idx);
    }
  }

  if (
    !content.includes("implementation(name: 'ffmpeg-kit-full-gpl', ext: 'aar')")
  ) {
    content = content.replace(/dependencies\s*{([\s\S]*?)}/m, (match, body) => {
      const extra =
        "    implementation(name: 'ffmpeg-kit-full-gpl', ext: 'aar')\n" +
        "    implementation 'com.arthenica:smart-exception-java:0.2.1'\n";
      return `dependencies {\n${extra}${body}}`;
    });
  }

  fs.writeFileSync(appGradlePath, content);
  console.log("✅ Patched android/app/build.gradle for FFmpegKit.");
};

const ensureAndroidRootGradle = () => {
  const rootGradlePath = path.join(appRoot, "android", "build.gradle");
  if (!fs.existsSync(rootGradlePath)) {
    return;
  }

  let content = fs.readFileSync(rootGradlePath, "utf8");

  if (
    !content.includes("flatDir {") ||
    !content.includes('dirs "$rootDir/libs"')
  ) {
    content = content.replace(
      /allprojects\s*{[\s\S]*?repositories\s*{([\s\S]*?)}}/m,
      (match, body) => {
        if (body.includes('dirs "$rootDir/libs"')) {
          return match;
        }
        const extra =
          "    flatDir {\n" + '      dirs "$rootDir/libs"\n' + "    }\n";
        return match.replace(
          /repositories\s*{([\s\S]*?)}/m,
          (reposMatch, reposBody) => `repositories {\n${reposBody}${extra}}`,
        );
      },
    );
  }

  fs.writeFileSync(rootGradlePath, content);
  console.log("✅ Patched android/build.gradle for FFmpegKit.");
};

const ensureFfmpegKitLibraryGradle = () => {
  let pkgJsonPath;
  try {
    pkgJsonPath = require.resolve("ffmpeg-kit-react-native/package.json", {
      paths: [appRoot],
    });
  } catch {
    console.warn(
      "⚠️ ffmpeg-kit-react-native not found in node_modules; skipping library Gradle patch.",
    );
    return;
  }

  const libRoot = path.dirname(pkgJsonPath);
  const gradlePath = path.join(libRoot, "android", "build.gradle");
  if (!fs.existsSync(gradlePath)) {
    return;
  }

  let content = fs.readFileSync(gradlePath, "utf8");

  content = content.replace(
    /minSdkVersion\s+safeExtGet\([^)]+\)[^\n]*/g,
    "minSdkVersion 24",
  );

  content = content.replace(
    /implementation\s+'com\.arthenica:ffmpeg-kit-[^']+'\s*\+\s*safePackageVersion\([^)]+\)[^\n]*\n/g,
    "",
  );

  if (
    !content.includes("implementation(name: 'ffmpeg-kit-full-gpl', ext: 'aar')")
  ) {
    content = content.replace(
      /dependencies\s*{([\s\S]*?)}/m,
      (match, body) =>
        `dependencies {\n    implementation(name: 'ffmpeg-kit-full-gpl', ext: 'aar')\n${body}}`,
    );
  }

  fs.writeFileSync(gradlePath, content);
  console.log("✅ Patched ffmpeg-kit-react-native/android/build.gradle.");
};

const setup = () => {
  ensureBinariesRelocated();
  ensureIosPodspec();
  ensureIosPodfile();
  ensureAndroidAppGradle();
  ensureAndroidRootGradle();
  ensureFfmpegKitLibraryGradle();
};

const verify = () => {
  console.log("🔍 Verifying FFmpeg binaries...");

  const iosTargetFile = path.join(appRoot, "ios", "libs", IOS_ZIP_NAME);
  const androidTargetFile = path.join(
    appRoot,
    "android",
    "libs",
    ANDROID_AAR_NAME,
  );

  if (!fs.existsSync(iosTargetFile) || !fs.existsSync(androidTargetFile)) {
    console.error(
      "❌ FFmpeg binaries are missing from their target locations.",
    );
    console.error(
      '💡 Please run "yarn install" (or "node scripts/manage-ffmpeg.js --setup") to relocate the FFmpeg binaries.',
    );
    process.exit(1);
  }

  console.log("✅ FFmpeg binaries found in ios/libs and android/libs.");
};

const args = process.argv.slice(2);
if (args.includes("--setup")) {
  setup();
} else if (args.includes("--verify")) {
  verify();
} else {
  console.log("Usage: node scripts/manage-ffmpeg.js [--setup | --verify]");
}
