import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system/legacy';
import type { Result } from '@/types/result';

export const generatePDF = async (
  transcript: string,
  soapNote: string,
  outputPath: string
): Promise<Result<string>> => {
  try {
    const html = `
      <html>
        <head>
          <style>
            body { font-family: Helvetica, sans-serif; padding: 40px; color: #333; }
            h1 { color: #208AEF; border-bottom: 2px solid #208AEF; padding-bottom: 10px; }
            h2 { color: #444; margin-top: 30px; }
            .section { margin-bottom: 20px; line-height: 1.6; }
            .label { font-weight: bold; color: #666; }
            .content { background: #f9f9f9; padding: 15px; border-radius: 8px; border: 1px solid #eee; }
            .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <h1>CaseScriptAI Medical Report</h1>
          
          <div class="section">
            <h2>Patient Transcript</h2>
            <div class="content">${transcript || 'No transcript provided.'}</div>
          </div>

          <div class="section">
            <h2>SOAP Note Analysis</h2>
            <div class="content">${soapNote || 'SOAP Note generation was used for analysis.'}</div>
          </div>

          <div class="footer">
            Generated by CaseScriptAI POC on ${new Date().toLocaleString()}
          </div>
        </body>
      </html>
    `;

    // Generate PDF to a temporary file
    const { uri } = await Print.printToFileAsync({ html });

    // Move the file to our desired output path
    // Ensure parent directory exists
    const dir = outputPath.substring(0, outputPath.lastIndexOf('/'));
    const dirInfo = await FileSystem.getInfoAsync(dir);
    if (!dirInfo.exists) {
      await FileSystem.makeDirectoryAsync(dir, { intermediates: true });
    }

    // Replace the existing file if it exists
    await FileSystem.moveAsync({
      from: uri,
      to: outputPath
    });

    return { success: true, data: outputPath };
  } catch (error) {
    console.error("[PDF Generator] Error:", error);
    return { 
      success: false, 
      error: error instanceof Error ? error.message : "Failed to generate PDF" 
    };
  }
};
